version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    # Optional: Uncomment the following lines to group updates
    # groups:
    #   dependencies:
    #     patterns:
    #       - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
