// This file is auto-generated by @hey-api/openapi-ts

import { client } from "./client.gen.js";
import type { Client, Options as Options2, TDataShape } from "./client/index.js";
import type {
  GetV1ExerciseHistoryExercisetemplateidData,
  GetV1ExerciseHistoryExercisetemplateidErrors,
  GetV1ExerciseHistoryExercisetemplateidResponses,
  GetV1ExerciseTemplatesData,
  GetV1ExerciseTemplatesErrors,
  GetV1ExerciseTemplatesExercisetemplateidData,
  GetV1ExerciseTemplatesExercisetemplateidErrors,
  GetV1ExerciseTemplatesExercisetemplateidResponses,
  GetV1ExerciseTemplatesResponses,
  GetV1RoutineFoldersData,
  GetV1RoutineFoldersErrors,
  GetV1RoutineFoldersFolderidData,
  GetV1RoutineFoldersFolderidErrors,
  GetV1RoutineFoldersFolderidResponses,
  GetV1RoutineFoldersResponses,
  GetV1RoutinesData,
  GetV1RoutinesErrors,
  GetV1RoutinesResponses,
  GetV1RoutinesRoutineidData,
  GetV1RoutinesRoutineidErrors,
  GetV1RoutinesRoutineidResponses,
  GetV1UserInfoData,
  GetV1UserInfoErrors,
  GetV1UserInfoResponses,
  GetV1WorkoutsCountData,
  GetV1WorkoutsCountResponses,
  GetV1WorkoutsData,
  GetV1WorkoutsErrors,
  GetV1WorkoutsEventsData,
  GetV1WorkoutsEventsErrors,
  GetV1WorkoutsEventsResponses,
  GetV1WorkoutsResponses,
  GetV1WorkoutsWorkoutidData,
  GetV1WorkoutsWorkoutidErrors,
  GetV1WorkoutsWorkoutidResponses,
  PostV1ExerciseTemplatesData,
  PostV1ExerciseTemplatesErrors,
  PostV1ExerciseTemplatesResponses,
  PostV1RoutineFoldersData,
  PostV1RoutineFoldersErrors,
  PostV1RoutineFoldersResponses,
  PostV1RoutinesData,
  PostV1RoutinesErrors,
  PostV1RoutinesResponses,
  PostV1WorkoutsData,
  PostV1WorkoutsErrors,
  PostV1WorkoutsResponses,
  PutV1RoutinesRoutineidData,
  PutV1RoutinesRoutineidErrors,
  PutV1RoutinesRoutineidResponses,
  PutV1WorkoutsWorkoutidData,
  PutV1WorkoutsWorkoutidErrors,
  PutV1WorkoutsWorkoutidResponses,
} from "./types.gen.js";
import {
  zGetV1ExerciseHistoryExercisetemplateidResponse,
  zGetV1ExerciseTemplatesExercisetemplateidResponse,
  zGetV1ExerciseTemplatesResponse,
  zGetV1RoutineFoldersFolderidResponse,
  zGetV1RoutineFoldersResponse,
  zGetV1RoutinesResponse,
  zGetV1RoutinesRoutineidResponse,
  zGetV1UserInfoResponse,
  zGetV1WorkoutsCountResponse,
  zGetV1WorkoutsEventsResponse,
  zGetV1WorkoutsResponse,
  zGetV1WorkoutsWorkoutidResponse,
  zPostV1ExerciseTemplatesResponse,
  zPostV1RoutineFoldersResponse,
  zPostV1RoutinesResponse,
  zPostV1WorkoutsResponse,
  zPutV1RoutinesRoutineidResponse,
  zPutV1WorkoutsWorkoutidResponse,
} from "./zod.gen.js";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Get a paginated list of workouts
 */
export const getV1Workouts = <ThrowOnError extends boolean = false>(
  options: Options<GetV1WorkoutsData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetV1WorkoutsResponses, GetV1WorkoutsErrors, ThrowOnError>({
    responseType: "json",
    responseValidator: async (data) => await zGetV1WorkoutsResponse.parseAsync(data),
    url: "/v1/workouts",
    ...options,
  });

/**
 * Create a new workout
 */
export const postV1Workouts = <ThrowOnError extends boolean = false>(
  options: Options<PostV1WorkoutsData, ThrowOnError>,
) =>
  (options.client ?? client).post<PostV1WorkoutsResponses, PostV1WorkoutsErrors, ThrowOnError>({
    responseType: "json",
    responseValidator: async (data) => await zPostV1WorkoutsResponse.parseAsync(data),
    url: "/v1/workouts",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get the total number of workouts on the account
 */
export const getV1WorkoutsCount = <ThrowOnError extends boolean = false>(
  options: Options<GetV1WorkoutsCountData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetV1WorkoutsCountResponses, unknown, ThrowOnError>({
    responseType: "json",
    responseValidator: async (data) => await zGetV1WorkoutsCountResponse.parseAsync(data),
    url: "/v1/workouts/count",
    ...options,
  });

/**
 * Retrieve a paged list of workout events (updates or deletes) since a given date. Events are ordered from newest to oldest. The intention is to allow clients to keep their local cache of workouts up to date without having to fetch the entire list of workouts.
 *
 * Returns a paginated array of workout events, indicating updates or deletions.
 */
export const getV1WorkoutsEvents = <ThrowOnError extends boolean = false>(
  options: Options<GetV1WorkoutsEventsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetV1WorkoutsEventsResponses,
    GetV1WorkoutsEventsErrors,
    ThrowOnError
  >({
    responseType: "json",
    responseValidator: async (data) => await zGetV1WorkoutsEventsResponse.parseAsync(data),
    url: "/v1/workouts/events",
    ...options,
  });

/**
 * Get a single workout’s complete details by the workoutId
 */
export const getV1WorkoutsWorkoutid = <ThrowOnError extends boolean = false>(
  options: Options<GetV1WorkoutsWorkoutidData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetV1WorkoutsWorkoutidResponses,
    GetV1WorkoutsWorkoutidErrors,
    ThrowOnError
  >({
    responseType: "json",
    responseValidator: async (data) => await zGetV1WorkoutsWorkoutidResponse.parseAsync(data),
    url: "/v1/workouts/{workoutId}",
    ...options,
  });

/**
 * Update an existing workout
 */
export const putV1WorkoutsWorkoutid = <ThrowOnError extends boolean = false>(
  options: Options<PutV1WorkoutsWorkoutidData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    PutV1WorkoutsWorkoutidResponses,
    PutV1WorkoutsWorkoutidErrors,
    ThrowOnError
  >({
    responseType: "json",
    responseValidator: async (data) => await zPutV1WorkoutsWorkoutidResponse.parseAsync(data),
    url: "/v1/workouts/{workoutId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get user info
 */
export const getV1UserInfo = <ThrowOnError extends boolean = false>(
  options: Options<GetV1UserInfoData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetV1UserInfoResponses, GetV1UserInfoErrors, ThrowOnError>({
    responseType: "json",
    responseValidator: async (data) => await zGetV1UserInfoResponse.parseAsync(data),
    url: "/v1/user/info",
    ...options,
  });

/**
 * Get a paginated list of routines
 */
export const getV1Routines = <ThrowOnError extends boolean = false>(
  options: Options<GetV1RoutinesData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetV1RoutinesResponses, GetV1RoutinesErrors, ThrowOnError>({
    responseType: "json",
    responseValidator: async (data) => await zGetV1RoutinesResponse.parseAsync(data),
    url: "/v1/routines",
    ...options,
  });

/**
 * Create a new routine
 */
export const postV1Routines = <ThrowOnError extends boolean = false>(
  options: Options<PostV1RoutinesData, ThrowOnError>,
) =>
  (options.client ?? client).post<PostV1RoutinesResponses, PostV1RoutinesErrors, ThrowOnError>({
    responseType: "json",
    responseValidator: async (data) => await zPostV1RoutinesResponse.parseAsync(data),
    url: "/v1/routines",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get a routine by its Id
 */
export const getV1RoutinesRoutineid = <ThrowOnError extends boolean = false>(
  options: Options<GetV1RoutinesRoutineidData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetV1RoutinesRoutineidResponses,
    GetV1RoutinesRoutineidErrors,
    ThrowOnError
  >({
    responseType: "json",
    responseValidator: async (data) => await zGetV1RoutinesRoutineidResponse.parseAsync(data),
    url: "/v1/routines/{routineId}",
    ...options,
  });

/**
 * Update an existing routine
 */
export const putV1RoutinesRoutineid = <ThrowOnError extends boolean = false>(
  options: Options<PutV1RoutinesRoutineidData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    PutV1RoutinesRoutineidResponses,
    PutV1RoutinesRoutineidErrors,
    ThrowOnError
  >({
    responseType: "json",
    responseValidator: async (data) => await zPutV1RoutinesRoutineidResponse.parseAsync(data),
    url: "/v1/routines/{routineId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get a paginated list of exercise templates available on the account.
 */
export const getV1ExerciseTemplates = <ThrowOnError extends boolean = false>(
  options: Options<GetV1ExerciseTemplatesData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetV1ExerciseTemplatesResponses,
    GetV1ExerciseTemplatesErrors,
    ThrowOnError
  >({
    responseType: "json",
    responseValidator: async (data) => await zGetV1ExerciseTemplatesResponse.parseAsync(data),
    url: "/v1/exercise_templates",
    ...options,
  });

/**
 * Create a new custom exercise template.
 */
export const postV1ExerciseTemplates = <ThrowOnError extends boolean = false>(
  options: Options<PostV1ExerciseTemplatesData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostV1ExerciseTemplatesResponses,
    PostV1ExerciseTemplatesErrors,
    ThrowOnError
  >({
    responseType: "json",
    responseValidator: async (data) => await zPostV1ExerciseTemplatesResponse.parseAsync(data),
    url: "/v1/exercise_templates",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get a single exercise template by id.
 */
export const getV1ExerciseTemplatesExercisetemplateid = <ThrowOnError extends boolean = false>(
  options: Options<GetV1ExerciseTemplatesExercisetemplateidData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetV1ExerciseTemplatesExercisetemplateidResponses,
    GetV1ExerciseTemplatesExercisetemplateidErrors,
    ThrowOnError
  >({
    responseType: "json",
    responseValidator: async (data) =>
      await zGetV1ExerciseTemplatesExercisetemplateidResponse.parseAsync(data),
    url: "/v1/exercise_templates/{exerciseTemplateId}",
    ...options,
  });

/**
 * Get a paginated list of routine folders available on the account.
 */
export const getV1RoutineFolders = <ThrowOnError extends boolean = false>(
  options: Options<GetV1RoutineFoldersData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetV1RoutineFoldersResponses,
    GetV1RoutineFoldersErrors,
    ThrowOnError
  >({
    responseType: "json",
    responseValidator: async (data) => await zGetV1RoutineFoldersResponse.parseAsync(data),
    url: "/v1/routine_folders",
    ...options,
  });

/**
 * Create a new routine folder. The folder will be created at index 0, and all other folders will have their indexes incremented.
 */
export const postV1RoutineFolders = <ThrowOnError extends boolean = false>(
  options: Options<PostV1RoutineFoldersData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostV1RoutineFoldersResponses,
    PostV1RoutineFoldersErrors,
    ThrowOnError
  >({
    responseType: "json",
    responseValidator: async (data) => await zPostV1RoutineFoldersResponse.parseAsync(data),
    url: "/v1/routine_folders",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get a single routine folder by id.
 */
export const getV1RoutineFoldersFolderid = <ThrowOnError extends boolean = false>(
  options: Options<GetV1RoutineFoldersFolderidData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetV1RoutineFoldersFolderidResponses,
    GetV1RoutineFoldersFolderidErrors,
    ThrowOnError
  >({
    responseType: "json",
    responseValidator: async (data) => await zGetV1RoutineFoldersFolderidResponse.parseAsync(data),
    url: "/v1/routine_folders/{folderId}",
    ...options,
  });

/**
 * Get exercise history for a specific exercise template
 */
export const getV1ExerciseHistoryExercisetemplateid = <ThrowOnError extends boolean = false>(
  options: Options<GetV1ExerciseHistoryExercisetemplateidData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetV1ExerciseHistoryExercisetemplateidResponses,
    GetV1ExerciseHistoryExercisetemplateidErrors,
    ThrowOnError
  >({
    responseType: "json",
    responseValidator: async (data) =>
      await zGetV1ExerciseHistoryExercisetemplateidResponse.parseAsync(data),
    url: "/v1/exercise_history/{exerciseTemplateId}",
    ...options,
  });
