// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

export const zPostWorkoutsRequestSet = z.object({
  type: z.enum(["warmup", "normal", "failure", "dropset"]).optional(),
  weight_kg: z.number().nullish(),
  reps: z.int().nullish(),
  distance_meters: z.int().nullish(),
  duration_seconds: z.int().nullish(),
  custom_metric: z.number().nullish(),
  rpe: z
    .union([
      z.literal(6),
      z.literal(7),
      z.literal(7.5),
      z.literal(8),
      z.literal(8.5),
      z.literal(9),
      z.literal(9.5),
      z.literal(10),
    ])
    .optional(),
});

export const zPostWorkoutsRequestExercise = z.object({
  exercise_template_id: z.string().optional(),
  superset_id: z.int().nullish(),
  notes: z.string().nullish(),
  sets: z.array(zPostWorkoutsRequestSet).optional(),
});

export const zPostWorkoutsRequestBody = z.object({
  workout: z
    .object({
      title: z.string().optional(),
      description: z.string().nullish(),
      start_time: z.string().optional(),
      end_time: z.string().optional(),
      is_private: z.boolean().optional(),
      exercises: z.array(zPostWorkoutsRequestExercise).optional(),
    })
    .optional(),
});

export const zPostRoutinesRequestSet = z.object({
  type: z.enum(["warmup", "normal", "failure", "dropset"]).optional(),
  weight_kg: z.number().nullish(),
  reps: z.int().nullish(),
  distance_meters: z.int().nullish(),
  duration_seconds: z.int().nullish(),
  custom_metric: z.number().nullish(),
  rep_range: z
    .object({
      start: z.number().optional(),
      end: z.number().optional(),
    })
    .nullish(),
});

export const zPostRoutinesRequestExercise = z.object({
  exercise_template_id: z.string().optional(),
  superset_id: z.int().nullish(),
  rest_seconds: z.int().nullish(),
  notes: z.string().nullish(),
  sets: z.array(zPostRoutinesRequestSet).optional(),
});

export const zPostRoutinesRequestBody = z.object({
  routine: z
    .object({
      title: z.string().optional(),
      folder_id: z.number().nullish(),
      notes: z.string().optional(),
      exercises: z.array(zPostRoutinesRequestExercise).optional(),
    })
    .optional(),
});

export const zPutRoutinesRequestSet = z.object({
  type: z.enum(["warmup", "normal", "failure", "dropset"]).optional(),
  weight_kg: z.number().nullish(),
  reps: z.int().nullish(),
  distance_meters: z.int().nullish(),
  duration_seconds: z.int().nullish(),
  custom_metric: z.number().nullish(),
  rep_range: z
    .object({
      start: z.number().nullish(),
      end: z.number().nullish(),
    })
    .nullish(),
});

export const zPutRoutinesRequestExercise = z.object({
  exercise_template_id: z.string().optional(),
  superset_id: z.int().nullish(),
  rest_seconds: z.int().nullish(),
  notes: z.string().nullish(),
  sets: z.array(zPutRoutinesRequestSet).optional(),
});

export const zPutRoutinesRequestBody = z.object({
  routine: z
    .object({
      title: z.string().optional(),
      notes: z.string().nullish(),
      exercises: z.array(zPutRoutinesRequestExercise).optional(),
    })
    .optional(),
});

export const zPostRoutineFolderRequestBody = z.object({
  routine_folder: z
    .object({
      title: z.string().optional(),
    })
    .optional(),
});

export const zSet = z.object({
  index: z.number().optional(),
  type: z.string().optional(),
  weight_kg: z.number().nullish(),
  reps: z.number().nullish(),
  distance_meters: z.number().nullish(),
  duration_seconds: z.number().nullish(),
  rpe: z.number().nullish(),
  custom_metric: z.number().nullish(),
});

export const zExercise = z.object({
  index: z.number().optional(),
  title: z.string().optional(),
  notes: z.string().optional(),
  exercise_template_id: z.string().optional(),
  supersets_id: z.number().nullish(),
  sets: z.array(zSet).optional(),
});

export const zExerciseHistoryEntry = z.object({
  workout_id: z.string().optional(),
  workout_title: z.string().optional(),
  workout_start_time: z.string().optional(),
  workout_end_time: z.string().optional(),
  exercise_template_id: z.string().optional(),
  weight_kg: z.number().nullish(),
  reps: z.int().nullish(),
  distance_meters: z.int().nullish(),
  duration_seconds: z.int().nullish(),
  rpe: z.number().nullish(),
  custom_metric: z.number().nullish(),
  set_type: z.string().optional(),
});

export const zCustomExerciseType = z.enum([
  "weight_reps",
  "reps_only",
  "bodyweight_reps",
  "bodyweight_assisted_reps",
  "duration",
  "weight_duration",
  "distance_duration",
  "short_distance_weight",
]);

export const zMuscleGroup = z.enum([
  "abdominals",
  "shoulders",
  "biceps",
  "triceps",
  "forearms",
  "quadriceps",
  "hamstrings",
  "calves",
  "glutes",
  "abductors",
  "adductors",
  "lats",
  "upper_back",
  "traps",
  "lower_back",
  "chest",
  "cardio",
  "neck",
  "full_body",
  "other",
]);

export const zEquipmentCategory = z.enum([
  "none",
  "barbell",
  "dumbbell",
  "kettlebell",
  "machine",
  "plate",
  "resistance_band",
  "suspension",
  "other",
]);

export const zExerciseTemplate = z.object({
  id: z.string().optional(),
  title: z.string().optional(),
  type: z.string().optional(),
  primary_muscle_group: z.string().optional(),
  secondary_muscle_groups: z.array(z.string()).optional(),
  is_custom: z.boolean().optional(),
});

export const zCreateCustomExerciseRequestBody = z.object({
  exercise: z.object({
    title: z.string().optional(),
    exercise_type: zCustomExerciseType.optional(),
    equipment_category: zEquipmentCategory.and(z.unknown()).optional(),
    muscle_group: zMuscleGroup.and(z.unknown()).optional(),
    other_muscles: z.array(zMuscleGroup).optional(),
  }),
});

export const zRoutineFolder = z.object({
  id: z.number().optional(),
  index: z.number().optional(),
  title: z.string().optional(),
  updated_at: z.string().optional(),
  created_at: z.string().optional(),
});

export const zRoutine = z.object({
  id: z.string().optional(),
  title: z.string().optional(),
  folder_id: z.number().nullish(),
  updated_at: z.string().optional(),
  created_at: z.string().optional(),
  exercises: z
    .array(
      z.object({
        index: z.number().optional(),
        title: z.string().optional(),
        rest_seconds: z.union([z.string(), z.number()]).optional(),
        notes: z.string().nullish(),
        exercise_template_id: z.string().optional(),
        supersets_id: z.number().nullish(),
        sets: z
          .array(
            z.object({
              index: z.number().optional(),
              type: z.string().optional(),
              weight_kg: z.number().nullish(),
              reps: z.number().nullish(),
              rep_range: z
                .object({
                  start: z.number().nullish(),
                  end: z.number().nullish(),
                })
                .nullish(),
              distance_meters: z.number().nullish(),
              duration_seconds: z.number().nullish(),
              rpe: z.number().nullish(),
              custom_metric: z.number().nullish(),
            }),
          )
          .optional(),
      }),
    )
    .optional(),
});

export const zUserInfo = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
  url: z.string().optional(),
});

export const zUserInfoResponse = z.object({
  data: zUserInfo.optional(),
});

export const zWorkout = z.object({
  id: z.string().optional(),
  title: z.string().optional(),
  routine_id: z.string().optional(),
  description: z.string().optional(),
  start_time: z.string().optional(),
  end_time: z.string().optional(),
  updated_at: z.string().optional(),
  created_at: z.string().optional(),
  exercises: z
    .array(
      z.object({
        index: z.number().optional(),
        title: z.string().optional(),
        notes: z.string().optional(),
        exercise_template_id: z.string().optional(),
        supersets_id: z.number().nullish(),
        sets: z
          .array(
            z.object({
              index: z.number().optional(),
              type: z.string().optional(),
              weight_kg: z.number().nullish(),
              reps: z.number().nullish(),
              distance_meters: z.number().nullish(),
              duration_seconds: z.number().nullish(),
              rpe: z.number().nullish(),
              custom_metric: z.number().nullish(),
            }),
          )
          .optional(),
      }),
    )
    .optional(),
});

export const zUpdatedWorkout = z.object({
  type: z.string(),
  workout: zWorkout,
});

export const zDeletedWorkout = z.object({
  type: z.string(),
  id: z.string(),
  deleted_at: z.string().optional(),
});

export const zPaginatedWorkoutEvents = z.object({
  page: z.int(),
  page_count: z.int(),
  events: z.array(z.union([zUpdatedWorkout, zDeletedWorkout])),
});

export const zGetV1WorkoutsData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z
    .object({
      page: z.int().optional().default(1),
      pageSize: z.int().optional().default(5),
    })
    .optional(),
  headers: z.object({
    "api-key": z.uuid(),
  }),
});

/**
 * A paginated list of workouts
 */
export const zGetV1WorkoutsResponse = z.object({
  page: z.int().optional(),
  page_count: z.int().optional(),
  workouts: z.array(zWorkout).optional(),
});

export const zPostV1WorkoutsData = z.object({
  body: zPostWorkoutsRequestBody,
  path: z.never().optional(),
  query: z.never().optional(),
  headers: z.object({
    "api-key": z.uuid(),
  }),
});

/**
 * The workout was successfully created
 */
export const zPostV1WorkoutsResponse = zWorkout;

export const zGetV1WorkoutsCountData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
  headers: z.object({
    "api-key": z.uuid(),
  }),
});

/**
 * The total count of workouts
 */
export const zGetV1WorkoutsCountResponse = z.object({
  workout_count: z.int().optional().default(42),
});

export const zGetV1WorkoutsEventsData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z
    .object({
      page: z.int().optional().default(1),
      pageSize: z.int().optional().default(5),
      since: z.string().optional().default("1970-01-01T00:00:00Z"),
    })
    .optional(),
  headers: z.object({
    "api-key": z.uuid(),
  }),
});

/**
 * A paginated list of workout events
 */
export const zGetV1WorkoutsEventsResponse = zPaginatedWorkoutEvents;

export const zGetV1WorkoutsWorkoutidData = z.object({
  body: z.never().optional(),
  path: z.object({
    workoutId: z.string(),
  }),
  query: z.never().optional(),
  headers: z.object({
    "api-key": z.uuid(),
  }),
});

/**
 * Success
 */
export const zGetV1WorkoutsWorkoutidResponse = zWorkout;

export const zPutV1WorkoutsWorkoutidData = z.object({
  body: zPostWorkoutsRequestBody,
  path: z.object({
    workoutId: z.string(),
  }),
  query: z.never().optional(),
  headers: z.object({
    "api-key": z.uuid(),
  }),
});

/**
 * The workout was successfully updated
 */
export const zPutV1WorkoutsWorkoutidResponse = zWorkout;

export const zGetV1UserInfoData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
  headers: z.object({
    "api-key": z.uuid(),
  }),
});

/**
 * The authenticated user's info
 */
export const zGetV1UserInfoResponse = zUserInfoResponse;

export const zGetV1RoutinesData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z
    .object({
      page: z.int().optional().default(1),
      pageSize: z.int().optional().default(5),
    })
    .optional(),
  headers: z.object({
    "api-key": z.uuid(),
  }),
});

/**
 * A paginated list of routines
 */
export const zGetV1RoutinesResponse = z.object({
  page: z.int().optional(),
  page_count: z.int().optional(),
  routines: z.array(zRoutine).optional(),
});

export const zPostV1RoutinesData = z.object({
  body: zPostRoutinesRequestBody,
  path: z.never().optional(),
  query: z.never().optional(),
  headers: z.object({
    "api-key": z.uuid(),
  }),
});

/**
 * The routine was successfully created
 */
export const zPostV1RoutinesResponse = zRoutine;

export const zGetV1RoutinesRoutineidData = z.object({
  body: z.never().optional(),
  path: z.object({
    routineId: z.string(),
  }),
  query: z.never().optional(),
  headers: z.object({
    "api-key": z.uuid(),
  }),
});

/**
 * The routine with the provided id
 */
export const zGetV1RoutinesRoutineidResponse = z.object({
  routine: zRoutine.optional(),
});

export const zPutV1RoutinesRoutineidData = z.object({
  body: zPutRoutinesRequestBody,
  path: z.object({
    routineId: z.string(),
  }),
  query: z.never().optional(),
  headers: z.object({
    "api-key": z.uuid(),
  }),
});

/**
 * The routine was successfully updated
 */
export const zPutV1RoutinesRoutineidResponse = zRoutine;

export const zGetV1ExerciseTemplatesData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z
    .object({
      page: z.int().optional().default(1),
      pageSize: z.int().optional().default(5),
    })
    .optional(),
  headers: z.object({
    "api-key": z.uuid(),
  }),
});

/**
 * A paginated list of exercise templates
 */
export const zGetV1ExerciseTemplatesResponse = z.object({
  page: z.int().optional().default(1),
  page_count: z.int().optional().default(5),
  exercise_templates: z.array(zExerciseTemplate).optional(),
});

export const zPostV1ExerciseTemplatesData = z.object({
  body: zCreateCustomExerciseRequestBody,
  path: z.never().optional(),
  query: z.never().optional(),
  headers: z.object({
    "api-key": z.uuid(),
  }),
});

/**
 * The exercise template was successfully created
 */
export const zPostV1ExerciseTemplatesResponse = z.object({
  id: z.int().optional(),
});

export const zGetV1ExerciseTemplatesExercisetemplateidData = z.object({
  body: z.never().optional(),
  path: z.object({
    exerciseTemplateId: z.string(),
  }),
  query: z.never().optional(),
  headers: z.object({
    "api-key": z.uuid(),
  }),
});

/**
 * Success
 */
export const zGetV1ExerciseTemplatesExercisetemplateidResponse = zExerciseTemplate;

export const zGetV1RoutineFoldersData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z
    .object({
      page: z.int().optional().default(1),
      pageSize: z.int().optional().default(5),
    })
    .optional(),
  headers: z.object({
    "api-key": z.uuid(),
  }),
});

/**
 * A paginated list of routine folders
 */
export const zGetV1RoutineFoldersResponse = z.object({
  page: z.int().optional().default(1),
  page_count: z.int().optional().default(5),
  routine_folders: z.array(zRoutineFolder).optional(),
});

export const zPostV1RoutineFoldersData = z.object({
  body: zPostRoutineFolderRequestBody,
  path: z.never().optional(),
  query: z.never().optional(),
  headers: z.object({
    "api-key": z.uuid(),
  }),
});

/**
 * The routine folder was successfully created
 */
export const zPostV1RoutineFoldersResponse = zRoutineFolder;

export const zGetV1RoutineFoldersFolderidData = z.object({
  body: z.never().optional(),
  path: z.object({
    folderId: z.string(),
  }),
  query: z.never().optional(),
  headers: z.object({
    "api-key": z.uuid(),
  }),
});

/**
 * Success
 */
export const zGetV1RoutineFoldersFolderidResponse = zRoutineFolder;

export const zGetV1ExerciseHistoryExercisetemplateidData = z.object({
  body: z.never().optional(),
  path: z.object({
    exerciseTemplateId: z.string(),
  }),
  query: z
    .object({
      start_date: z.iso.datetime().optional(),
      end_date: z.iso.datetime().optional(),
    })
    .optional(),
  headers: z.object({
    "api-key": z.uuid(),
  }),
});

/**
 * A list of exercise history entries
 */
export const zGetV1ExerciseHistoryExercisetemplateidResponse = z.object({
  exercise_history: z.array(zExerciseHistoryEntry).optional(),
});
